# Generated by Django 5.2.10 on 2026-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('investment_type', models.CharField(blank=True, choices=[('medical', 'Medical Unit'), ('commercial', 'Commercial Unit'), ('pharmacy', 'Pharmacy'), ('restaurant', 'Restaurant/Cafe'), ('other', 'Other')], max_length=20, null=True, verbose_name='Investment Type')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified Lead'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referrer URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Contacted At')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ajei_contac_created_558942_idx'), models.Index(fields=['status'], name='ajei_contac_status_2448b4_idx'), models.Index(fields=['email'], name='ajei_contac_email_d0e405_idx')],
            },
        ),
    ]
