# Generated by Django 5.2.7 on 2026-01-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=500, verbose_name='Page Path')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Page Title')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referrer URL')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Language')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Viewed At')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='ajei_pagevi_viewed__e4d401_idx'), models.Index(fields=['page_path'], name='ajei_pagevi_page_pa_6039f8_idx'), models.Index(fields=['ip_address'], name='ajei_pagevi_ip_addr_ce8f1d_idx')],
            },
        ),
    ]
